name: Playwright Automation Tests

on:
  schedule:
  # Run every day at 8:00 PM Central Time
  - cron: '0 20 * * *'
    timezone: "America/Chicago"

  # Allows you to run it manually from Github
  workflow_dispatch:

jobs:
  tests-chromium:
    name: playwright-tests-chromium
    runs-on: ubuntu-latest
    env:
      HEADLESS: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install
      - name: Run all tests in chromium
        run: npm run test
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/dashboard/
        
  tests-msedge:
    name: playwright-tests-msedge
    runs-on: ubuntu-latest
    env:
      HEADLESS: true
      BROWSER: 'edge'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install
      - name: Run all tests in msedge
        run: npm run test
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/dashboard/

  tests-webkit:
    name: playwright-tests-webkit
    runs-on: ubuntu-latest
    env:
      HEADLESS: true
      BROWSER: 'webkit'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install
      - name: Run all tests in webkit
        run: npm run test
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/dashboard/

  tests-firefox:
    name: playwright-tests-firefox
    runs-on: ubuntu-latest
    env:
      HEADLESS: true
      BROWSER: 'firefox'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install
      - name: Run all tests firefox
        run: npm run test
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/dashboard/